
-- =========================================================
-- MEDICONTROL - SISTEMA MEDICO DE SEGUIMIENTO
-- Oracle 21c / Compatible con estructura tradicional Oracle
-- Usuario recomendado: CLINICA_APP
-- Conexion recomendada: CLINICA_PROYECTO / Service Name XEPDB1
-- =========================================================

-- =========================================================
-- LIMPIEZA OPCIONAL
-- Ejecuta este bloque solo si quieres borrar y recrear todo.
-- =========================================================
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables
        WHERE table_name IN (
            'ALERTAS','REGISTRO_PRESION','REGISTRO_GLUCOSA','SEGUIMIENTO_DOSIS',
            'DOSIS_PROGRAMADAS','TRATAMIENTO_DETALLE','TRATAMIENTOS','MEDICAMENTOS',
            'DIAGNOSTICOS','CONSULTAS','PACIENTES','ENFERMERAS','DOCTORES',
            'TIPOS_PRESION','TIPOS_DIABETES','USUARIOS','ROLES'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;

    FOR s IN (
        SELECT sequence_name FROM user_sequences
        WHERE sequence_name LIKE 'SEQ_MED_%'
    ) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- =========================================================
-- TABLAS BASE
-- =========================================================

CREATE TABLE ROLES (
    ID_ROL NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(150)
);

CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER PRIMARY KEY,
    ID_ROL NUMBER NOT NULL,
    USERNAME VARCHAR2(60) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    INTENTOS_FALLIDOS NUMBER DEFAULT 0 NOT NULL,
    BLOQUEADO CHAR(1) DEFAULT 'N' NOT NULL,
    DEBE_CAMBIAR_PASSWORD CHAR(1) DEFAULT 'S' NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_USUARIOS_ROLES FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL),
    CONSTRAINT CHK_USUARIOS_BLOQUEADO CHECK (BLOQUEADO IN ('S','N')),
    CONSTRAINT CHK_USUARIOS_CAMBIO CHECK (DEBE_CAMBIAR_PASSWORD IN ('S','N')),
    CONSTRAINT CHK_USUARIOS_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE DOCTORES (
    ID_DOCTOR NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER UNIQUE,
    NOMBRES VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    COLEGIADO VARCHAR2(50),
    ESPECIALIDAD VARCHAR2(100),
    TELEFONO VARCHAR2(30),
    CORREO VARCHAR2(120),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT FK_DOCTORES_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT CHK_DOCTORES_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE ENFERMERAS (
    ID_ENFERMERA NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER UNIQUE,
    NOMBRES VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(30),
    CORREO VARCHAR2(120),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT FK_ENFERMERAS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT CHK_ENFERMERAS_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE TIPOS_DIABETES (
    ID_TIPO_DIABETES NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(80) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(250)
);

CREATE TABLE TIPOS_PRESION (
    ID_TIPO_PRESION NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(80) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(250)
);

CREATE TABLE PACIENTES (
    ID_PACIENTE NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL UNIQUE,
    ID_DOCTOR NUMBER,
    ID_ENFERMERA_REGISTRA NUMBER,
    NOMBRES VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    DPI VARCHAR2(25) UNIQUE,
    FECHA_NACIMIENTO DATE,
    SEXO VARCHAR2(15),
    TELEFONO VARCHAR2(30),
    CORREO VARCHAR2(120),
    DIRECCION VARCHAR2(250),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT FK_PACIENTES_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_PACIENTES_DOCTOR FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTORES(ID_DOCTOR),
    CONSTRAINT FK_PACIENTES_ENFERMERA FOREIGN KEY (ID_ENFERMERA_REGISTRA) REFERENCES ENFERMERAS(ID_ENFERMERA),
    CONSTRAINT CHK_PACIENTES_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO')),
    CONSTRAINT CHK_PACIENTES_SEXO CHECK (SEXO IS NULL OR SEXO IN ('M','F','OTRO'))
);

CREATE TABLE CONSULTAS (
    ID_CONSULTA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    ID_DOCTOR NUMBER NOT NULL,
    FECHA_CONSULTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MOTIVO VARCHAR2(250),
    SINTOMAS VARCHAR2(500),
    OBSERVACIONES VARCHAR2(1000),
    PESO_KG NUMBER(6,2),
    ALTURA_CM NUMBER(6,2),
    GLUCOSA NUMBER(6,2),
    PRESION_SISTOLICA NUMBER,
    PRESION_DIASTOLICA NUMBER,
    CONSTRAINT FK_CONSULTAS_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    CONSTRAINT FK_CONSULTAS_DOCTOR FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTORES(ID_DOCTOR)
);

CREATE TABLE DIAGNOSTICOS (
    ID_DIAGNOSTICO NUMBER PRIMARY KEY,
    ID_CONSULTA NUMBER NOT NULL,
    ID_TIPO_DIABETES NUMBER,
    ID_TIPO_PRESION NUMBER,
    DESCRIPCION VARCHAR2(1000) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_DIAG_CONSULTA FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTAS(ID_CONSULTA),
    CONSTRAINT FK_DIAG_DIABETES FOREIGN KEY (ID_TIPO_DIABETES) REFERENCES TIPOS_DIABETES(ID_TIPO_DIABETES),
    CONSTRAINT FK_DIAG_PRESION FOREIGN KEY (ID_TIPO_PRESION) REFERENCES TIPOS_PRESION(ID_TIPO_PRESION)
);

CREATE TABLE MEDICAMENTOS (
    ID_MEDICAMENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(300),
    UNIDAD VARCHAR2(40) DEFAULT 'TABLETA' NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT CHK_MED_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE TRATAMIENTOS (
    ID_TRATAMIENTO NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    ID_DOCTOR NUMBER NOT NULL,
    ID_CONSULTA NUMBER,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    INDICACIONES VARCHAR2(1000),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_TRAT_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    CONSTRAINT FK_TRAT_DOCTOR FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTORES(ID_DOCTOR),
    CONSTRAINT FK_TRAT_CONSULTA FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTAS(ID_CONSULTA),
    CONSTRAINT CHK_TRAT_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT CHK_TRAT_ESTADO CHECK (ESTADO IN ('ACTIVO','FINALIZADO','SUSPENDIDO'))
);

CREATE TABLE TRATAMIENTO_DETALLE (
    ID_TRATAMIENTO_DETALLE NUMBER PRIMARY KEY,
    ID_TRATAMIENTO NUMBER NOT NULL,
    ID_MEDICAMENTO NUMBER NOT NULL,
    DOSIS VARCHAR2(120) NOT NULL,
    FRECUENCIA_HORAS NUMBER DEFAULT 24 NOT NULL,
    HORA_INICIO VARCHAR2(5) DEFAULT '08:00' NOT NULL,
    DURACION_DIAS NUMBER NOT NULL,
    CANTIDAD_TOTAL NUMBER DEFAULT 0 NOT NULL,
    CANTIDAD_RESTANTE NUMBER DEFAULT 0 NOT NULL,
    INDICACION_DETALLE VARCHAR2(500),
    CONSTRAINT FK_TRAT_DET_TRAT FOREIGN KEY (ID_TRATAMIENTO) REFERENCES TRATAMIENTOS(ID_TRATAMIENTO),
    CONSTRAINT FK_TRAT_DET_MED FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTOS(ID_MEDICAMENTO),
    CONSTRAINT CHK_TRAT_DET_FREC CHECK (FRECUENCIA_HORAS > 0),
    CONSTRAINT CHK_TRAT_DET_DIAS CHECK (DURACION_DIAS > 0),
    CONSTRAINT CHK_TRAT_DET_CANT CHECK (CANTIDAD_TOTAL >= 0 AND CANTIDAD_RESTANTE >= 0)
);

CREATE TABLE DOSIS_PROGRAMADAS (
    ID_DOSIS NUMBER PRIMARY KEY,
    ID_TRATAMIENTO_DETALLE NUMBER NOT NULL,
    ID_PACIENTE NUMBER NOT NULL,
    FECHA_PROGRAMADA TIMESTAMP NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    FECHA_REPORTADA TIMESTAMP,
    CONSTRAINT FK_DOSIS_TRAT_DET FOREIGN KEY (ID_TRATAMIENTO_DETALLE) REFERENCES TRATAMIENTO_DETALLE(ID_TRATAMIENTO_DETALLE),
    CONSTRAINT FK_DOSIS_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    CONSTRAINT CHK_DOSIS_ESTADO CHECK (ESTADO IN ('PENDIENTE','TOMADA','OMITIDA','ATRASADA'))
);

CREATE TABLE SEGUIMIENTO_DOSIS (
    ID_SEGUIMIENTO NUMBER PRIMARY KEY,
    ID_DOSIS NUMBER NOT NULL,
    ID_PACIENTE NUMBER NOT NULL,
    FECHA_REPORTE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ESTADO_REPORTE VARCHAR2(20) NOT NULL,
    OBSERVACION VARCHAR2(500),
    CONSTRAINT FK_SEG_DOSIS FOREIGN KEY (ID_DOSIS) REFERENCES DOSIS_PROGRAMADAS(ID_DOSIS),
    CONSTRAINT FK_SEG_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    CONSTRAINT CHK_SEG_ESTADO CHECK (ESTADO_REPORTE IN ('TOMADA','OMITIDA'))
);

CREATE TABLE REGISTRO_GLUCOSA (
    ID_GLUCOSA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    VALOR NUMBER(6,2) NOT NULL,
    UNIDAD VARCHAR2(20) DEFAULT 'mg/dL' NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    OBSERVACION VARCHAR2(500),
    CONSTRAINT FK_GLUCOSA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    CONSTRAINT CHK_GLUCOSA_VALOR CHECK (VALOR > 0)
);

CREATE TABLE REGISTRO_PRESION (
    ID_PRESION NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    SISTOLICA NUMBER NOT NULL,
    DIASTOLICA NUMBER NOT NULL,
    PULSO NUMBER,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    OBSERVACION VARCHAR2(500),
    CONSTRAINT FK_PRESION_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    CONSTRAINT CHK_PRESION_VALORES CHECK (SISTOLICA > 0 AND DIASTOLICA > 0)
);

CREATE TABLE ALERTAS (
    ID_ALERTA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    ID_DOCTOR NUMBER,
    ID_DOSIS NUMBER,
    TIPO_ALERTA VARCHAR2(50) NOT NULL,
    MENSAJE VARCHAR2(500) NOT NULL,
    FECHA_ALERTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    FECHA_ATENDIDA TIMESTAMP,
    CONSTRAINT FK_ALERTA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    CONSTRAINT FK_ALERTA_DOCTOR FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTORES(ID_DOCTOR),
    CONSTRAINT FK_ALERTA_DOSIS FOREIGN KEY (ID_DOSIS) REFERENCES DOSIS_PROGRAMADAS(ID_DOSIS),
    CONSTRAINT CHK_ALERTA_ESTADO CHECK (ESTADO IN ('PENDIENTE','ATENDIDA'))
);

-- =========================================================
-- SECUENCIAS
-- =========================================================
CREATE SEQUENCE SEQ_MED_ROLES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_USUARIOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_DOCTORES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_ENFERMERAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_PACIENTES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_TIPOS_DIABETES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_TIPOS_PRESION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_CONSULTAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_DIAGNOSTICOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_MEDICAMENTOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_TRATAMIENTOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_TRAT_DET START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_DOSIS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_SEGUIMIENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_GLUCOSA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_PRESION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MED_ALERTAS START WITH 1 INCREMENT BY 1;

-- =========================================================
-- INDICES
-- =========================================================
CREATE INDEX IDX_USUARIOS_ROL ON USUARIOS(ID_ROL);
CREATE INDEX IDX_PACIENTES_DOCTOR ON PACIENTES(ID_DOCTOR);
CREATE INDEX IDX_CONSULTAS_PACIENTE ON CONSULTAS(ID_PACIENTE);
CREATE INDEX IDX_CONSULTAS_DOCTOR ON CONSULTAS(ID_DOCTOR);
CREATE INDEX IDX_TRAT_PACIENTE ON TRATAMIENTOS(ID_PACIENTE);
CREATE INDEX IDX_DOSIS_PACIENTE_ESTADO ON DOSIS_PROGRAMADAS(ID_PACIENTE, ESTADO);
CREATE INDEX IDX_DOSIS_FECHA ON DOSIS_PROGRAMADAS(FECHA_PROGRAMADA);
CREATE INDEX IDX_ALERTAS_DOCTOR_ESTADO ON ALERTAS(ID_DOCTOR, ESTADO);
CREATE INDEX IDX_GLUCOSA_PACIENTE ON REGISTRO_GLUCOSA(ID_PACIENTE);
CREATE INDEX IDX_PRESION_PACIENTE ON REGISTRO_PRESION(ID_PACIENTE);

-- =========================================================
-- VISTAS DE REPORTE
-- =========================================================
CREATE OR REPLACE VIEW VW_PACIENTES_RESUMEN AS
SELECT 
    P.ID_PACIENTE,
    P.NOMBRES || ' ' || P.APELLIDOS AS PACIENTE,
    NVL(D.NOMBRES || ' ' || D.APELLIDOS, 'Sin doctor') AS DOCTOR,
    U.USERNAME,
    P.TELEFONO,
    P.ESTADO,
    P.FECHA_REGISTRO
FROM PACIENTES P
INNER JOIN USUARIOS U ON U.ID_USUARIO = P.ID_USUARIO
LEFT JOIN DOCTORES D ON D.ID_DOCTOR = P.ID_DOCTOR;

CREATE OR REPLACE VIEW VW_DOSIS_PENDIENTES AS
SELECT
    DP.ID_DOSIS,
    DP.ID_PACIENTE,
    P.NOMBRES || ' ' || P.APELLIDOS AS PACIENTE,
    M.NOMBRE AS MEDICAMENTO,
    TD.DOSIS,
    DP.FECHA_PROGRAMADA,
    DP.ESTADO
FROM DOSIS_PROGRAMADAS DP
INNER JOIN PACIENTES P ON P.ID_PACIENTE = DP.ID_PACIENTE
INNER JOIN TRATAMIENTO_DETALLE TD ON TD.ID_TRATAMIENTO_DETALLE = DP.ID_TRATAMIENTO_DETALLE
INNER JOIN MEDICAMENTOS M ON M.ID_MEDICAMENTO = TD.ID_MEDICAMENTO
WHERE DP.ESTADO = 'PENDIENTE';

CREATE OR REPLACE VIEW VW_ALERTAS_DOCTOR AS
SELECT
    A.ID_ALERTA,
    A.ID_DOCTOR,
    A.ID_PACIENTE,
    P.NOMBRES || ' ' || P.APELLIDOS AS PACIENTE,
    A.TIPO_ALERTA,
    A.MENSAJE,
    A.FECHA_ALERTA,
    A.ESTADO
FROM ALERTAS A
INNER JOIN PACIENTES P ON P.ID_PACIENTE = A.ID_PACIENTE;

-- =========================================================
-- PAQUETE DE SEGUIMIENTO
-- =========================================================
CREATE OR REPLACE PACKAGE PKG_SEGUIMIENTO AS
    FUNCTION DOSIS_PENDIENTES(P_ID_PACIENTE NUMBER) RETURN NUMBER;
    PROCEDURE GENERAR_DOSIS_TRATAMIENTO(P_ID_TRATAMIENTO NUMBER);
    PROCEDURE GENERAR_ALERTAS_ATRASADAS;
END PKG_SEGUIMIENTO;
/

CREATE OR REPLACE PACKAGE BODY PKG_SEGUIMIENTO AS

    FUNCTION DOSIS_PENDIENTES(P_ID_PACIENTE NUMBER) RETURN NUMBER IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM DOSIS_PROGRAMADAS
        WHERE ID_PACIENTE = P_ID_PACIENTE
          AND ESTADO = 'PENDIENTE';

        RETURN V_TOTAL;
    END DOSIS_PENDIENTES;

    PROCEDURE GENERAR_DOSIS_TRATAMIENTO(P_ID_TRATAMIENTO NUMBER) IS
        V_ID_PACIENTE NUMBER;
        V_FECHA_INICIO DATE;
        V_FECHA_FIN DATE;
        V_FECHA_ACTUAL DATE;
        V_FECHA_DOSIS TIMESTAMP;
        V_HORAS NUMBER;
        V_DIAS NUMBER;
        V_ITER NUMBER;
        V_TOTAL_DOSIS NUMBER;
    BEGIN
        SELECT ID_PACIENTE, FECHA_INICIO, FECHA_FIN
        INTO V_ID_PACIENTE, V_FECHA_INICIO, V_FECHA_FIN
        FROM TRATAMIENTOS
        WHERE ID_TRATAMIENTO = P_ID_TRATAMIENTO;

        FOR D IN (
            SELECT ID_TRATAMIENTO_DETALLE, FRECUENCIA_HORAS, HORA_INICIO, DURACION_DIAS
            FROM TRATAMIENTO_DETALLE
            WHERE ID_TRATAMIENTO = P_ID_TRATAMIENTO
        ) LOOP
            V_HORAS := D.FRECUENCIA_HORAS;
            V_DIAS := D.DURACION_DIAS;
            V_TOTAL_DOSIS := FLOOR((V_DIAS * 24) / V_HORAS);
            V_ITER := 0;

            WHILE V_ITER < V_TOTAL_DOSIS LOOP
                V_FECHA_DOSIS :=
                    TO_TIMESTAMP(
                        TO_CHAR(V_FECHA_INICIO, 'YYYY-MM-DD') || ' ' || NVL(D.HORA_INICIO, '08:00'),
                        'YYYY-MM-DD HH24:MI'
                    ) + NUMTODSINTERVAL(V_ITER * V_HORAS, 'HOUR');

                IF CAST(V_FECHA_DOSIS AS DATE) <= V_FECHA_FIN + 1 THEN
                    INSERT INTO DOSIS_PROGRAMADAS (
                        ID_DOSIS,
                        ID_TRATAMIENTO_DETALLE,
                        ID_PACIENTE,
                        FECHA_PROGRAMADA,
                        ESTADO
                    ) VALUES (
                        SEQ_MED_DOSIS.NEXTVAL,
                        D.ID_TRATAMIENTO_DETALLE,
                        V_ID_PACIENTE,
                        V_FECHA_DOSIS,
                        'PENDIENTE'
                    );
                END IF;

                V_ITER := V_ITER + 1;
            END LOOP;
        END LOOP;
    END GENERAR_DOSIS_TRATAMIENTO;

    PROCEDURE GENERAR_ALERTAS_ATRASADAS IS
    BEGIN
        FOR R IN (
            SELECT 
                DP.ID_DOSIS,
                DP.ID_PACIENTE,
                P.ID_DOCTOR,
                M.NOMBRE AS MEDICAMENTO,
                DP.FECHA_PROGRAMADA
            FROM DOSIS_PROGRAMADAS DP
            INNER JOIN PACIENTES P ON P.ID_PACIENTE = DP.ID_PACIENTE
            INNER JOIN TRATAMIENTO_DETALLE TD ON TD.ID_TRATAMIENTO_DETALLE = DP.ID_TRATAMIENTO_DETALLE
            INNER JOIN MEDICAMENTOS M ON M.ID_MEDICAMENTO = TD.ID_MEDICAMENTO
            WHERE DP.ESTADO = 'PENDIENTE'
              AND DP.FECHA_PROGRAMADA < CURRENT_TIMESTAMP - INTERVAL '2' HOUR
              AND NOT EXISTS (
                    SELECT 1 FROM ALERTAS A
                    WHERE A.ID_DOSIS = DP.ID_DOSIS
                      AND A.TIPO_ALERTA = 'DOSIS_NO_REPORTADA'
              )
        ) LOOP
            UPDATE DOSIS_PROGRAMADAS
            SET ESTADO = 'ATRASADA'
            WHERE ID_DOSIS = R.ID_DOSIS;

            INSERT INTO ALERTAS (
                ID_ALERTA,
                ID_PACIENTE,
                ID_DOCTOR,
                ID_DOSIS,
                TIPO_ALERTA,
                MENSAJE,
                ESTADO
            ) VALUES (
                SEQ_MED_ALERTAS.NEXTVAL,
                R.ID_PACIENTE,
                R.ID_DOCTOR,
                R.ID_DOSIS,
                'DOSIS_NO_REPORTADA',
                'El paciente no reportó la dosis programada del medicamento ' || R.MEDICAMENTO,
                'PENDIENTE'
            );
        END LOOP;
    END GENERAR_ALERTAS_ATRASADAS;

END PKG_SEGUIMIENTO;
/

-- =========================================================
-- PAQUETE DE REPORTES
-- =========================================================
CREATE OR REPLACE PACKAGE PKG_REPORTES AS
    FUNCTION TOTAL_PACIENTES_DOCTOR(P_ID_DOCTOR NUMBER) RETURN NUMBER;
    FUNCTION TOTAL_ALERTAS_PENDIENTES(P_ID_DOCTOR NUMBER) RETURN NUMBER;
END PKG_REPORTES;
/

CREATE OR REPLACE PACKAGE BODY PKG_REPORTES AS

    FUNCTION TOTAL_PACIENTES_DOCTOR(P_ID_DOCTOR NUMBER) RETURN NUMBER IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM PACIENTES
        WHERE ID_DOCTOR = P_ID_DOCTOR
          AND ESTADO = 'ACTIVO';

        RETURN V_TOTAL;
    END TOTAL_PACIENTES_DOCTOR;

    FUNCTION TOTAL_ALERTAS_PENDIENTES(P_ID_DOCTOR NUMBER) RETURN NUMBER IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM ALERTAS
        WHERE ID_DOCTOR = P_ID_DOCTOR
          AND ESTADO = 'PENDIENTE';

        RETURN V_TOTAL;
    END TOTAL_ALERTAS_PENDIENTES;

END PKG_REPORTES;
/

-- =========================================================
-- DATOS INICIALES
-- Nota: Las contraseñas demo se guardan temporalmente como texto.
-- La API las convierte a hash BCrypt en el primer login correcto.
-- Password demo para todos: admin123
-- =========================================================

INSERT INTO ROLES VALUES (SEQ_MED_ROLES.NEXTVAL, 'ADMIN', 'Administrador del sistema');
INSERT INTO ROLES VALUES (SEQ_MED_ROLES.NEXTVAL, 'ENFERMERA', 'Usuario web de enfermería');
INSERT INTO ROLES VALUES (SEQ_MED_ROLES.NEXTVAL, 'DOCTOR', 'Usuario web de doctor');
INSERT INTO ROLES VALUES (SEQ_MED_ROLES.NEXTVAL, 'PACIENTE', 'Usuario de app móvil');

INSERT INTO TIPOS_DIABETES VALUES (SEQ_MED_TIPOS_DIABETES.NEXTVAL, 'Diabetes Tipo 1', 'El cuerpo no produce suficiente insulina.');
INSERT INTO TIPOS_DIABETES VALUES (SEQ_MED_TIPOS_DIABETES.NEXTVAL, 'Diabetes Tipo 2', 'El cuerpo no usa correctamente la insulina.');
INSERT INTO TIPOS_DIABETES VALUES (SEQ_MED_TIPOS_DIABETES.NEXTVAL, 'Diabetes Gestacional', 'Diabetes detectada durante el embarazo.');

INSERT INTO TIPOS_PRESION VALUES (SEQ_MED_TIPOS_PRESION.NEXTVAL, 'Normal', 'Presión dentro del rango esperado.');
INSERT INTO TIPOS_PRESION VALUES (SEQ_MED_TIPOS_PRESION.NEXTVAL, 'Hipertensión Etapa 1', 'Presión arterial elevada en etapa inicial.');
INSERT INTO TIPOS_PRESION VALUES (SEQ_MED_TIPOS_PRESION.NEXTVAL, 'Hipertensión Etapa 2', 'Presión arterial elevada en etapa avanzada.');
INSERT INTO TIPOS_PRESION VALUES (SEQ_MED_TIPOS_PRESION.NEXTVAL, 'Crisis Hipertensiva', 'Presión muy alta que requiere atención.');

INSERT INTO MEDICAMENTOS VALUES (SEQ_MED_MEDICAMENTOS.NEXTVAL, 'Metformina 850mg', 'Medicamento usado para control de glucosa.', 'TABLETA', 'ACTIVO');
INSERT INTO MEDICAMENTOS VALUES (SEQ_MED_MEDICAMENTOS.NEXTVAL, 'Losartán 50mg', 'Medicamento usado para presión arterial.', 'TABLETA', 'ACTIVO');
INSERT INTO MEDICAMENTOS VALUES (SEQ_MED_MEDICAMENTOS.NEXTVAL, 'Insulina NPH', 'Insulina de acción intermedia.', 'UNIDAD', 'ACTIVO');

-- Usuarios base
INSERT INTO USUARIOS (ID_USUARIO, ID_ROL, USERNAME, PASSWORD_HASH, DEBE_CAMBIAR_PASSWORD)
VALUES (SEQ_MED_USUARIOS.NEXTVAL, (SELECT ID_ROL FROM ROLES WHERE NOMBRE='ADMIN'), 'admin', 'admin123', 'N');

INSERT INTO USUARIOS (ID_USUARIO, ID_ROL, USERNAME, PASSWORD_HASH, DEBE_CAMBIAR_PASSWORD)
VALUES (SEQ_MED_USUARIOS.NEXTVAL, (SELECT ID_ROL FROM ROLES WHERE NOMBRE='DOCTOR'), 'doctor.demo', 'admin123', 'N');

INSERT INTO DOCTORES (ID_DOCTOR, ID_USUARIO, NOMBRES, APELLIDOS, COLEGIADO, ESPECIALIDAD, TELEFONO, CORREO)
VALUES (
    SEQ_MED_DOCTORES.NEXTVAL,
    (SELECT ID_USUARIO FROM USUARIOS WHERE USERNAME='doctor.demo'),
    'Alberto',
    'Marroquin',
    'MED-001',
    'Medicina General',
    '5555-0001',
    'doctor.demo@clinicamedicontrol.com'
);

INSERT INTO USUARIOS (ID_USUARIO, ID_ROL, USERNAME, PASSWORD_HASH, DEBE_CAMBIAR_PASSWORD)
VALUES (SEQ_MED_USUARIOS.NEXTVAL, (SELECT ID_ROL FROM ROLES WHERE NOMBRE='ENFERMERA'), 'enfermera.demo', 'admin123', 'N');

INSERT INTO ENFERMERAS (ID_ENFERMERA, ID_USUARIO, NOMBRES, APELLIDOS, TELEFONO, CORREO)
VALUES (
    SEQ_MED_ENFERMERAS.NEXTVAL,
    (SELECT ID_USUARIO FROM USUARIOS WHERE USERNAME='enfermera.demo'),
    'Carolina',
    'Gomez',
    '5555-0002',
    'enfermera.demo@clinicamedicontrol.com'
);

COMMIT;

-- =========================================================
-- PRUEBAS RAPIDAS
-- =========================================================
-- SELECT * FROM ROLES;
-- SELECT * FROM USUARIOS;
-- SELECT * FROM DOCTORES;
-- SELECT * FROM ENFERMERAS;
-- SELECT * FROM MEDICAMENTOS;
